name: invoice_simple
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  ###
  flutter_bloc: ^9.0.0
  flutter_contacts: ^1.1.9+2
  flutter_svg: ^2.1.0
  dotted_border: ^2.1.0
  get_it: ^8.0.3
  go_router: ^15.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  pdf: ^3.11.3
  printing: ^5.14.2
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  signature: ^6.3.0
  path_provider: ^2.1.5
  smooth_page_indicator: ^1.2.1
  purchases_flutter: ^8.8.1
  purchases_ui_flutter: ^8.8.1
  ###
dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
flutter:
  uses-material-design: true
  assets:
    - assets/images/png/
    - assets/images/svg/
flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/helpers/
  filename: app_assets.dart
  field_prefix: null
fonts:
  - family: Montserrat
    fonts:
      - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        weight: 400
      - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
        weight: 500
      - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
        weight: 700
      - asset: assets/fonts/montserrat/Montserrat-ExtraBold.ttf
        weight: 800
  - family: Poppins
    fonts:
      - asset: assets/fonts/poppins/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/poppins/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/poppins/Poppins-Bold.ttf
        weight: 700